### PR TITLE
purge memorycache because it doesn't work cross-platform

### PR DESCRIPTION
**Pull request by baronfel**
I found while trying to mimic the official TP template that @dsyme made with the YamlProvider (because I still can't use the prerelease version on netstandard2.0 libraries yet) that System.Runtime.Caching doesn't work cross-platform, so here I ripped it out. I also changed the package template to include pdbs if present as well as just a general dependency update.

### CODE REVIEW

**Comment by baronfel** [comment]
Here's what just the Yaml portion looks like as a TP based on the template: https://github.com/baronfel/FSharp.Data.YamlProvider

**Comment by baronfel** [comment]
while this is _a_ problem, it's not the only problem. trying to use the TP in a .netstandard library while modifying the `debug` function to write to a file and try/catching the Yaml type provider construction results in the following log: 

```shell
✗ cat ../../debug.log
[10/17/2018 10:15:10 AM] Type Settings does not contain TopLevelUnknown property.

[10/17/18 10:15:43 AM] Type Settings does not contain TopLevelUnknown property.
```

I've been looking for where this string could come from (specifically the 'does not contain' portion because I expect the 'Settings' and 'TopLevelUnknown' parts to be placeholders) in this repo, the TPSDK, and VisualFsharp itself with no luck.

**Comment by baronfel** [comment]
I am dumb and it's coming from some tests while building the TP itself.

**Comment by baronfel** [comment]
ok now this works in .netstandard2.0 libraries. The biggest functional change is the change to `ConfigTypeProvider.fs` where I added the `addDefaultProbingLocation = true` so that we could locate the `YamlDotNet` dependency at runtime.

With this, when I manually build and override the package used in a .netstandard2.0 library at work, I can compile successfully, which I cannot do with alpha2.

**Comment by sergey-tihon** [comment]
First of all, thank you @baronfel for this PR.

As I remember `System.Runtime.Caching` is design time dependency, the only reason to keep is to speed up IDE experience. 

Why cannot we reference [System.Runtime.Caching](https://www.nuget.org/packages/System.Runtime.Caching/) and then pack `System.Runtime.Caching.dll` (netstandard version or both) as design-time only dependency for `FSharp.Configuration`?

**Comment by baronfel** [comment]
it _may_ be possible, but because there is no separate design-time vs runtime component in this TP I think we will fail at runtime.

if we reworked the TP to have separate runtime and design-time dependencies it might be possible to do such a thing.

**Comment by sergey-tihon** [comment]
Ok, I think that I got it...
Should I merge this PR? (it is ready?)

**Comment by baronfel** [comment]
I believe it is ready, yes. I am concerned that tests didn't reproduce the failure I had at work, but we can address that later 😄

**Comment by sergey-tihon** [comment]
IRC, I've tried TP in `netcore` project and it worked with `alpha2`.
So, your case is kind of special, because you did `netstandard` library that uses TP, I though that most of usages will be in executable runtimes (like net45, netcore, mono or something else)

**Pull request merged**
